#!/bin/sh

function prowl () {
    curl -f 'https://api.prowlapp.com/publicapi/add' -d "apikey=`cat ~/.prowlkey | head -c 40`" --data-binary "description=$1" -d "application=`hostname`" > /dev/null 2>&1
}

function tostorage () {
    scp -r "$1" stephenroller.com:~/www/stephenroller.com/storage/uploaded/
    echo "http://stephenroller.com/storage/uploaded/`basename $1`"
}

function torandom () {
    scp -r "$1" stephenroller.com:~/www/stephenroller.com/storage/random/
    echo "http://stephenroller.com/storage/random/`basename $1`"
}

function freq() {
    sort $* | uniq -c | sort -rn;
}

function sample() {
    awk 'BEGIN { srand() } {print rand() "|" $0}' | sort -gn | head -n $1 | sed 's/^[0-9.]*|//'
}


