#!/bin/sh

function fbcurl () {
    curl `fwdproxy-config curl` $@
}

function prowl () {
    fbcurl -f 'https://api.prowlapp.com/publicapi/add' -d "apikey=`cat ~/.prowlkey | head -c 40`" --data-binary "description=$1" -d "application=`hostname`" > /dev/null 2>&1
}

function freq() {
    sort $* | uniq -c | sort -rn;
}

function cds () {
    cd $SCRATCH/$1
}


function cdp () {
    cd ~/working/parlai/$1
}

function jqg () {
    jq -c "select($@)"
}
