#!/bin/sh

# places i often keep bin files:
export PATH=".:$HOME/software/bin:$HOME/bin:$PATH"

# choice editor, pager
export PAGER="less -R"
export EDITOR="vim"
export GIT_PAGER="less -R"

# python stuff
export PYTHONSTARTUP="$HOME/.pythonrc.py"
export PYTHONPATH=$PYTHONPATH:~/.pylibs


