#!/bin/sh

# places i often keep bin files:
export PATH="/usr/local/bin:.:$HOME/software/bin:$HOME/bin:$HOME/working/dotfiles/bin:$PATH:./bin"

# choice editor, pager
#export PAGER="less -R"
export EDITOR="vim"
export GIT_PAGER="less -R"

# python stuff
export PYTHONIOENCODING="utf-8"

# helpful for limiting fzf stuff
export FZF_DEFAULT_COMMAND='ag -f -g ""'

export SCRATCH=/data/users/roller
